#!/usr/bin/env bash

echo "Setting up vendor/harfbuzz"
script/generate-hb-version vendor/harfbuzz/src/hb-version.h

echo "Compiling glyph_renderer"
em++ \
  --bind \
  -o glyph_renderer.js \
  src/bindings/*.cc \
  src/core/*.cc \
  -xc++ \
  -O3 \
  -I src/core \
  -I src/bindings \
  -I vendor/harfbuzz/src \
  -I vendor/freetype2/include \
  -s TOTAL_MEMORY=134217728 \
  --memory-init-file 0 \
  -s USE_HARFBUZZ=1 \
  -s USE_FREETYPE=1

echo "Cleaning up vendor/harfbuzz"
rm vendor/harfbuzz/src/hb-version.h
